### ISSUE TITLE
Request Data functionality

### ISSUE THREAD

**Issue by payvint** [skalenetwork/oracle-sdk#4]
There is a input type "Request Data" which we need to simplify for end users.

There is suggestion how we can simplify it:
1. Store schainNames(mainnet, testnet) and their endpoints, so user just need to pass a name and endpoint would be automatically filled in
2. Eth_call: it should be able to pass a standard eth_call object or ethers.js contract call object, with optional param chain(default Ethereum). Chain can be a name like Binance Smart Chain, Polygon or etc. Or it should be possible to pass a chain endpoint

**Comment by TheGreatAxios** [comment]
@payvint 

- For the first point agree but only for hub chains on mainnet and testnet. dApps can PR to add support for their own chain if they want or open an issue with label "Request SKALE Chain"
- For the second point agree

**Comment by payvint** [comment]
> @payvint
> 
> * For the first point agree but only for hub chains on mainnet and testnet. dApps can PR to add support for their own chain if they want or open an issue with label "Request SKALE Chain"
> * For the second point agree

You are right, support it!
